name: Checklister

services:

  # MySQL database handling storing all data in a persistent volume
  database:
    image: mysql

    env_file:
      - .env.db

    networks:
      - checklister-network

    volumes:
      - checklister-db:/var/lib/mysql


  # FastAPI backend, listening locally on port 8000
  # Secrets are passed via .env file. MAKE SURE TO CHANGE IT
  backend:
    image: todo-app-backend

    env_file:
      - .env
      - .env.db

    environment:
      MYSQL_HOST: database

    ports:
      - 8000:8000

    networks:
      - checklister-network

    depends_on:
      - database


  # React app frontend, served using Nginx
  # Exposing port 80
  frontend:
    image: todo-app-frontend
    # build:
    #   context: ./frontend
    #   args:
    #     REACT_APP_API_URL: $REACT_APP_API_URL

    # environment:
    #   REACT_APP_API_URL: "http://backend:8000"
      
    networks:
      - checklister-network

    ports:
      - 80:80


# Custom network to ensure inter-container communication
networks:
  checklister-network:


# Custom volume to persist MySQL data
volumes:
  checklister-db: