name: Checklister

services:
  # FastAPI backend, listening locally on port 8000
  backend:
    image: 271122/checklister-backend

    environment:
      MYSQL_HOST: database

    ports:
      - 8000:8000

    networks:
      - checklister-network


  # React app frontend, served using Nginx. Exposing port 80
  frontend:
    image: 271122/checklister-frontend

    environment:
      REACT_APP_API_URL: "http://backend:8000"
      
    networks:
      - checklister-network

    ports:
      - 80:80


# Custom network to ensure inter-container communication
networks:
  checklister-network:


# Custom volume to persist MySQL data
volumes:
  checklister-db:
    driver: local
    name: checklister-db
