apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: checklister-db
  name: checklister-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
